[package]
name = "played-rs"
version = "0.1.0"
authors = ["Colin Adler <cadler@coder.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
redis = "0.11.0"
tokio = "0.2.0-alpha.2"
foundationdb = "0.3.0"
eetf = "0.4"

[[bin]]
name = "played-rs"
path = "main.rs"
